const express = require('express');
const router = express.Router();
const ctrl = require('../../controllers/admin/studentsController');
const { upload } = require('../../config/multer');
router.get('/', ctrl.index);
router.get('/new', ctrl.create);
router.post('/', upload('students').single('photo'), ctrl.store);
router.get('/:id', ctrl.show);
router.get('/:id/edit', ctrl.edit);
router.put('/:id', upload('students').single('photo'), ctrl.update);
router.delete('/:id', ctrl.destroy);
router.get('/:id/id-card', ctrl.generateIdCard);
module.exports = router;
